services:
  ###
  # Project Services
  ###

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        VITE_API_PREFIX: "/"
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      NODE_ENV: production
      PGSTRING: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres-prod:5432/postgres
      PGMATE_ADMIN_SECRET: ${PGMATE_ADMIN_SECRET:-pgmate}
    depends_on:
      postgres-prod:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz | grep -qE "(200|404)" || exit 1',
        ]
      interval: 1s
      timeout: 1s
      retries: 10

  ###
  # External Images
  ###

  postgres-prod:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 20
