FROM python:3.9
RUN pip install requests
RUN pip install PyJWT
RUN pip install psycopg2
RUN pip install pandas
RUN pip install openpyxl
RUN pip install minify-html
RUN pip install tabulate
RUN pip install faker
RUN pip install minify-html
RUN pip install psycopg2-binary tabulate humanize