### List all packages
GET http://localhost:8080/admin/v1/packages

###

GET https://legendary-winner-7wvpg4wjqqgcx69j-8080.app.github.dev/admin/v1/packages
Content-Type: application/json
x-pgmate-admin-secret: pgmate


###
GET https://legendary-winner-7wvpg4wjqqgcx69j-8080.app.github.dev/admin/v1/admin/status

### Add a new package
POST http://localhost:8080/packages/new-package
Content-Type: application/json

{
  "name": "new-package",
  "version": "1.0.0"
}